[package]
name = "react-native-skia"
version = "0.1.0"
edition = "2018"

[dependencies]
gl = "0.14.0"
glutin = "0.27.0"
glutin_gles2_sys = "0.1.5"
skia-safe = { version = "0.43.0", features = ["gl"] }

