language: rust
os:
  - linux
  - osx
rust:
  - stable
  - nightly
matrix:
  allow_failures:
    - rust: nightly
notifications:
  email: false
before_script:
  - export PATH=$PATH:~/.cargo/bin
script:
  - cargo build --verbose
  - cargo test --verbose